version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package install
      - mvn surefire-report:report
reports: #New
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports

artifacts:
  files:
    - target/*.jar

  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes
